name: build_and_deploy
env:
  IMAGE_NAME: eldrynor/efrei_m2_tp_cicd:latest
on:
  push:
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Set up Python 12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: install requirements
        run: python -m pip install -r requirements.txt
      - name: launch unit test
        run: python -m unittest discover -s tests/unit/

  e2e_tests:
    needs: unit_test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Set up Python 12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: install requests
        run: python -m pip install requests
      - name: build de l'api
        run: docker build -t e2e_api .
      - name: Démarrer l'api
        run: docker run -d --name api -p 3000:3000 e2e_api && sleep 3
      - name: launch E2E tests
        run: python -m unittest discover -s tests/e2e
      - name: suppression du container
        run: |
          docker stop api
          docker rm api

  build_and_push:
    needs: e2e_tests
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.HUB_USERNAME }}
          password: ${{ secrets.HUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build and push image
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ vars.DEPLOY_IP }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - name: clef SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.pem
          chmod 600 ~/.ssh/private.pem
          echo "ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts"
          ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts
      - name: docker
        run: |
          ssh -i ~/.ssh/private.pem ubuntu@$SSH_HOST << EOF
            IMAGE_NAME="${{ env.IMAGE_NAME }}"
            CONTAINER_NAME="${{ env.CONTAINER_NAME }}"
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
            docker pull $IMAGE_NAME
            docker run --name $CONTAINER_NAME -d --restart unless-stopped -p 3000:3000 $IMAGE_NAME
          EOF
        env:
          CONTAINER_NAME: api-tp-cicd
