name: build_and_deploy
env:
  IMAGE_NAME: eldrynor/efrei_m2_tp_cicd:latest
on:
  push:
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.HUB_USERNAME }}
          password: ${{ secrets.HUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        # with:
        #   driver-opts: network=host
      - name: Build and push image
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}
