name: build_and_deploy
env:
  IMAGE_NAME: eldrynor/efrei_m2_tp_cicd:latest
on:
  push:
jobs:
  # build_and_push:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v4
  #       with:
  #         username: ${{ vars.HUB_USERNAME }}
  #         password: ${{ secrets.HUB_TOKEN }}
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v4
  #     - name: Build and push image
  #       uses: docker/build-push-action@v7
  #       with:
  #         push: true
  #         tags: ${{ env.IMAGE_NAME }}

  deploy:
    runs-on: ubuntu-latest
    # needs: build_and_push
    env:
      SSH_HOST: ${{ vars.DEPLOY_IP }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - name: clef SSH
        run: |
          mkdir ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.pem
          chmod 600 ~/.ssh/private.pem
          echo "ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts"
          ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts         
      - name: docker
        run: |
          ssh -i ~/.ssh/private.pem ubuntu@$SSH_HOST docker ps
